server:
    port: 8080

spring:
    application:
        name: todoapp
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
    jmx:
        enabled: false
    liquibase:
        enabled: false
        user: todoapp
        password: todoapp
        locations: classpath:db/migration
        url: jdbc:postgresql://localhost:5432/todoapp
    datasource:
        url: jdbc:postgresql://localhost:5432/todoapp
        username: todoapp
        password: todoapp
    servlet:
        multipart:
            enabled: true
            location: ../uploads/